
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.OpenDevicePartnership]
url = "https://raw.githubusercontent.com/OpenDevicePartnership/rust-crate-audits/main/audits.toml"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.embassy-imxrt]
audit-as-crates-io = false

[policy.keyberon]
audit-as-crates-io = false

[[exemptions.crc]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-run"

[[exemptions.futures-task]]
version = "0.3.32"
criteria = "safe-to-run"

[[exemptions.futures-timer]]
version = "3.0.3"
criteria = "safe-to-run"

[[exemptions.generator]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.14.0"
criteria = "safe-to-deploy"

[[exemptions.pretty_assertions]]
version = "1.4.1"
criteria = "safe-to-run"

[[exemptions.proc-macro-crate]]
version = "3.5.0"
criteria = "safe-to-run"

[[exemptions.rustc-demangle]]
version = "0.1.26"
criteria = "safe-to-run"

[[exemptions.semver]]
version = "1.0.28"
criteria = "safe-to-run"

[[exemptions.toml_datetime]]
version = "1.1.1+spec-1.1.0"
criteria = "safe-to-run"

[[exemptions.toml_edit]]
version = "0.25.11+spec-1.1.0"
criteria = "safe-to-run"

[[exemptions.toml_parser]]
version = "1.1.2+spec-1.1.0"
criteria = "safe-to-run"

[[exemptions.winnow]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.yansi]]
version = "1.0.1"
criteria = "safe-to-run"
